/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Migration {
  'data' : [] | [MigrationData],
  'name' : string,
  'version' : bigint,
}
export interface MigrationData {
  'entries' : Array<[Principal, Array<[string, VaultEntry]>]>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VaultEntry {
  'id' : string,
  'title' : string,
  'entryType' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'updatedAt' : bigint,
  'encryptedPayload' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<[string, string, string, Array<string>], string>,
  'deleteEntry' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntries' : ActorMethod<[], Array<VaultEntry>>,
  'getEntriesByTag' : ActorMethod<[string], Array<VaultEntry>>,
  'getEntriesByType' : ActorMethod<[string], Array<VaultEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'migrate' : ActorMethod<[Migration], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEntry' : ActorMethod<[string, string, string, Array<string>], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];