/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VaultEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'entryType' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'encryptedPayload' : IDL.Text,
});
export const MigrationData = IDL.Record({
  'entries' : IDL.Vec(
    IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Tuple(IDL.Text, VaultEntry)))
  ),
});
export const Migration = IDL.Record({
  'data' : IDL.Opt(MigrationData),
  'name' : IDL.Text,
  'version' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(VaultEntry)], ['query']),
  'getEntriesByTag' : IDL.Func([IDL.Text], [IDL.Vec(VaultEntry)], ['query']),
  'getEntriesByType' : IDL.Func([IDL.Text], [IDL.Vec(VaultEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'migrate' : IDL.Func([Migration], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VaultEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'entryType' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'encryptedPayload' : IDL.Text,
  });
  const MigrationData = IDL.Record({
    'entries' : IDL.Vec(
      IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Tuple(IDL.Text, VaultEntry)))
    ),
  });
  const Migration = IDL.Record({
    'data' : IDL.Opt(MigrationData),
    'name' : IDL.Text,
    'version' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(VaultEntry)], ['query']),
    'getEntriesByTag' : IDL.Func([IDL.Text], [IDL.Vec(VaultEntry)], ['query']),
    'getEntriesByType' : IDL.Func([IDL.Text], [IDL.Vec(VaultEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'migrate' : IDL.Func([Migration], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };